name: Build ActuarialAI Calculator

on:
  push:
    branches: [ main, upsilon-dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3 python3-pip
        
    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
        
    - name: Build web simulator
      run: |
        source $EMSDK_PATH/emsdk_env.sh
        make PLATFORM=simulator TARGET=web -j2
        
    - name: Package web simulator
      run: |
        mkdir -p web-build
        cp output/simulator/web/simulator.html web-build/
        cp output/simulator/web/epsilon.js web-build/
        cp output/simulator/web/background.jpg web-build/
        cd web-build
        zip -r ../actuarial-ai-web-simulator.zip .
        
    - name: Upload web simulator
      uses: actions/upload-artifact@v4
      with:
        name: actuarial-ai-web-simulator
        path: actuarial-ai-web-simulator.zip
